import express from 'express';import cors from 'cors';import dotenv from 'dotenv';import {MongoClient,ObjectId} from 'mongodb';import {initializeApp,cert,getApps} from 'firebase-admin/app';import {getAuth} from 'firebase-admin/auth';dotenv.config();const app=express();app.use(cors({origin:true}));app.use(express.json());const port=process.env.PORT||3000;let db=null;
async function connectDb(){if(!process.env.MONGODB_URI)return;const client=new MongoClient(process.env.MONGODB_URI);await client.connect();db=client.db(process.env.MONGODB_DB||'universal_tracker');console.log('MongoDB connected')}
function initFirebase(){if(getApps().length)return;const key=process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g,'\n');if(process.env.FIREBASE_PROJECT_ID&&process.env.FIREBASE_CLIENT_EMAIL&&key)initializeApp({credential:cert({projectId:process.env.FIREBASE_PROJECT_ID,clientEmail:process.env.FIREBASE_CLIENT_EMAIL,privateKey:key})})}
async function auth(req,res,next){if(process.env.REQUIRE_AUTH!=='true'){req.uid='demo-user';return next()}try{initFirebase();const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Missing Firebase token'});req.uid=(await getAuth().verifyIdToken(h.slice(7))).uid;next()}catch{return res.status(401).json({error:'Invalid Firebase token'})}}
async function goldLive(){if(!process.env.GOLDAPI_KEY)throw new Error('GOLDAPI_KEY not configured');const r=await fetch('https://www.goldapi.io/api/XAU/INR',{headers:{'x-access-token':process.env.GOLDAPI_KEY}});if(!r.ok)throw new Error('Gold API request failed');const x=await r.json();return{price:x.price,pricePerGram:x.price_per_gram??x.price/31.1034768,changePercent:x.chp||0,timestamp:x.timestamp}}
app.get('/api/health',(req,res)=>res.json({ok:true,db:Boolean(db)}));
app.get('/api/dashboard',auth,async(req,res)=>{try{const gold=await goldLive().catch(()=>null);const counts=db?await Promise.all([db.collection('trackers').countDocuments({uid:req.uid,type:'product'}),db.collection('trackers').countDocuments({uid:req.uid,type:'job'}),db.collection('medicalAlerts').countDocuments({uid:req.uid}),db.collection('trackers').countDocuments({uid:req.uid,type:'flight'})]):[0,0,0,0];res.json({gold,products:counts[0],jobs:counts[1],medical:counts[2],flights:counts[3]})}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/gold/live',auth,async(req,res)=>{try{res.json(await goldLive())}catch(e){res.status(503).json({error:e.message})}});
app.get('/api/products/search',auth,async(req,res)=>{try{if(!process.env.SERPAPI_KEY)throw new Error('SERPAPI_KEY not configured');const u=new URL('https://serpapi.com/search');u.searchParams.set('engine','google_shopping');u.searchParams.set('q',req.query.q||'');u.searchParams.set('gl','in');u.searchParams.set('hl','en');u.searchParams.set('api_key',process.env.SERPAPI_KEY);const r=await fetch(u);if(!r.ok)throw new Error('Product API request failed');const x=await r.json();res.json({results:(x.shopping_results||[]).map(p=>({title:p.title,price:p.price,source:p.source,thumbnail:p.thumbnail,url:p.product_link}))})}catch(e){res.status(503).json({error:e.message})}});
app.get('/api/jobs/search',auth,async(req,res)=>{try{if(!process.env.ADZUNA_APP_ID||!process.env.ADZUNA_APP_KEY)throw new Error('ADZUNA credentials not configured');const u=new URL('https://api.adzuna.com/v1/api/jobs/in/search/1');u.searchParams.set('app_id',process.env.ADZUNA_APP_ID);u.searchParams.set('app_key',process.env.ADZUNA_APP_KEY);u.searchParams.set('results_per_page','20');u.searchParams.set('what',req.query.what||'');if(req.query.location)u.searchParams.set('where',req.query.location);u.searchParams.set('content-type','application/json');const r=await fetch(u);if(!r.ok)throw new Error('Jobs API request failed');const x=await r.json();res.json({results:(x.results||[]).map(j=>({title:j.title,company:j.company?.display_name||'',location:j.location?.display_name||'',url:j.redirect_url}))})}catch(e){res.status(503).json({error:e.message})}});
app.get('/api/medical/alerts',auth,async(req,res)=>{try{const u=new URL('https://api.fda.gov/drug/enforcement.json');if(req.query.q)u.searchParams.set('search',`product_description:${req.query.q}`);u.searchParams.set('limit','20');const r=await fetch(u);if(r.status===404)return res.json({results:[]});if(!r.ok)throw new Error('Medical API request failed');const x=await r.json();res.json({results:(x.results||[]).map(a=>({product:a.product_description||'',reason:a.reason_for_recall||'',status:a.status||'',date:a.recall_initiation_date||''}))})}catch(e){res.status(503).json({error:e.message})}});
async function amadeusToken(){if(!process.env.AMADEUS_CLIENT_ID||!process.env.AMADEUS_CLIENT_SECRET)throw new Error('Amadeus credentials not configured');const base=process.env.AMADEUS_BASE_URL||'https://test.api.amadeus.com';const r=await fetch(`${base}/v1/security/oauth2/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'client_credentials',client_id:process.env.AMADEUS_CLIENT_ID,client_secret:process.env.AMADEUS_CLIENT_SECRET})});if(!r.ok)throw new Error('Amadeus authentication failed');return(await r.json()).access_token}
app.get('/api/flights/search',auth,async(req,res)=>{try{const base=process.env.AMADEUS_BASE_URL||'https://test.api.amadeus.com';const token=await amadeusToken();const u=new URL(`${base}/v2/shopping/flight-offers`);u.searchParams.set('originLocationCode',req.query.origin||'COK');u.searchParams.set('destinationLocationCode',req.query.destination||'DEL');u.searchParams.set('departureDate',req.query.date);u.searchParams.set('adults',req.query.adults||'1');u.searchParams.set('currencyCode','INR');u.searchParams.set('max','20');const r=await fetch(u,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Flight API request failed');const x=await r.json();res.json({results:(x.data||[]).map(f=>({price:f.price?.grandTotal,currency:f.price?.currency,airline:f.validatingAirlineCodes?.[0]||'',departure:f.itineraries?.[0]?.segments?.[0]?.departure?.at,arrival:f.itineraries?.[0]?.segments?.at(-1)?.arrival?.at,stops:(f.itineraries?.[0]?.segments?.length||1)-1}))})}catch(e){res.status(503).json({error:e.message})}});
app.get('/api/trackers',auth,async(req,res)=>{if(!db)return res.json({results:[]});res.json({results:await db.collection('trackers').find({uid:req.uid}).sort({createdAt:-1}).toArray()})});app.post('/api/trackers',auth,async(req,res)=>{if(!db)return res.status(503).json({error:'MongoDB not configured'});const r=await db.collection('trackers').insertOne({...req.body,uid:req.uid,createdAt:new Date(),updatedAt:new Date()});res.json({id:r.insertedId.toString()})});app.delete('/api/trackers/:id',auth,async(req,res)=>{if(!db)return res.status(503).json({error:'MongoDB not configured'});await db.collection('trackers').deleteOne({_id:new ObjectId(req.params.id),uid:req.uid});res.json({ok:true})});
app.listen(port,async()=>{await connectDb().catch(e=>console.error('MongoDB:',e.message));console.log(`Universal Tracker API listening on ${port}`)});