import React from 'react';

const nav = ['Dashboard','Gold Tracker','Products','Job Search','Medical Alerts','Flight Scan','Crypto','Expenses','Subscriptions','Settings'];

export default function App(){
  const [page,setPage]=React.useState('Dashboard');
  const [dark,setDark]=React.useState(false);
  const [logged,setLogged]=React.useState(false);
  const bg=dark?'#111827':'#f7f8fc';
  if(!logged) return <div style={{minHeight:'100vh',display:'grid',gridTemplateColumns:'1fr 560px',background:'linear-gradient(110deg,#faf8ff,#f4efff)',fontFamily:'Inter,Arial,sans-serif',color:'#111827'}}><div style={{padding:'110px 80px'}}><div style={{fontWeight:700,color:'#5138d9',fontSize:24}}>▦ Universal Tracker</div><div style={{fontSize:13,color:'#555',marginTop:2}}>Track life, stay ahead.</div><h1 style={{fontSize:36,marginTop:55,marginBottom:12}}>Your All-in-One<br/><span style={{color:'#5b35df'}}>Tracking Platform</span></h1><p style={{color:'#666',maxWidth:430}}>Monitor gold, jobs, products, flights, expenses, medical alerts, and more in one place.</p><p>🟡 Real-time tracking</p><p>🔵 Smart alerts & notifications</p><p>🟣 Beautiful, simple dashboard</p></div><div style={{display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{background:'#fff',width:330,padding:30,borderRadius:12,boxShadow:'0 15px 45px #bbb8',marginRight:70}}><h2>Welcome back</h2><small>Sign in to continue</small><input placeholder="Email" style={input}/><input placeholder="Password" type="password" style={input}/><button style={button} onClick={()=>setLogged(true)}>Sign In →</button><div style={{textAlign:'center',margin:'18px 0'}}>or</div><button style={{...button,background:'#fff',color:'#333',border:'1px solid #ddd'}}>G  Continue with Google</button><p style={{fontSize:12,textAlign:'center',color:'#666'}}>Don't have an account? Sign up</p></div></div></div>;
  return <div style={{minHeight:'100vh',background:bg,color:dark?'#fff':'#111827',fontFamily:'Inter,Arial,sans-serif',display:'flex'}}><aside style={{width:220,background:dark?'#171e2e':'#15112b',color:'#fff',padding:18,boxSizing:'border-box'}}><div style={{fontWeight:700,fontSize:17,marginBottom:28}}>▦ Universal Tracker</div>{nav.map(x=><div key={x} onClick={()=>setPage(x)} style={{padding:'10px 12px',borderRadius:7,margin:'3px 0',cursor:'pointer',background:page===x?'#6638ed':'transparent',fontSize:13}}>{x}</div>)}<div style={{marginTop:30,fontSize:11,color:'#aaa'}}>⚙ Settings</div></aside><main style={{flex:1}}><header style={{height:54,borderBottom:'1px solid #ddd',display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 22px',background:dark?'#111827':'#fff'}}><b style={{fontSize:13}}>{page}</b><div>⌕　🔔　🟣 <span style={{fontSize:12}}>Welcome</span></div></header><section style={{padding:28,maxWidth:1100}}><h1 style={{fontSize:20,margin:'0 0 6px'}}>{page} <small style={{fontSize:11,color:'#888'}}> / overview</small></h1>{page==='Dashboard'?<Dashboard/>:<Feature title={page}/>}</section></main></div>
}
const input={display:'block',width:'100%',boxSizing:'border-box',padding:11,margin:'13px 0',border:'1px solid #ddd',borderRadius:6};
const button={width:'100%',padding:11,border:0,borderRadius:6,background:'#6335e5',color:'#fff',fontWeight:600};
function Dashboard(){return <><p style={{color:'#777'}}>Dashboard Overview</p><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12}}>{['Gold Price','Products Tracked','Active Jobs','Medical Alerts','Flights Tracked','Expenses Today','Expenses This Month','Upcoming Bills'].map((x,i)=><div style={{background:'#fff',border:'1px solid #e7e7ed',borderRadius:8,padding:18,minHeight:65}} key={x}><div style={{fontSize:12,color:'#777'}}>{x}</div><strong style={{fontSize:20}}>{i===0?'₹11,650/g':'0'}</strong></div>)}</div><button style={{position:'fixed',right:28,bottom:22,width:44,height:44,borderRadius:50,fontSize:24,...button}}>+</button></>}
function Feature({title}){return <div style={{background:'#fff',border:'1px solid #e3e3e8',borderRadius:8,padding:22,marginTop:20}}><h3>{title}</h3><p style={{color:'#777'}}>No data found</p><p style={{fontSize:13}}>Connect your service or add a tracker to start monitoring it.</p></div>}
